services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5900:5900"      
    environment:
      - NODE_ENV=development
      - DISPLAY=:99
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/libs/rektCaptcha:/app/libs/rektCaptcha
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge