services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5900:5900"
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=3000
      - VNC_PORT=5900
      - DISPLAY=:99
    networks:
      - app-network
    # Tambahkan healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_FRONTEND_PORT=5173
      - VITE_BACKEND_URL=http://localhost:3000
      - VITE_ALLOWED_HOSTS=localhost
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  app-network:
    name: app-network
    driver: bridge